baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hugo-simple" 
sectionPagesMenu = 'main'

[pagination]
  disableAliases = false
  pagerSize = 30
  path = 'page' 