baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Kittens Overview'
theme = "hugo-simple" 
sectionPagesMenu = 'main'
Copyright = "stephan meyn 2025"

mainSections =['upgrades', 'craft', 'buildings']
[params]
hideRSSLink = true
toc = true

[pagination]
  disableAliases = false
  pagerSize = 30
  path = 'page' 